Dockerfile optimizations

diff --git a/Dockerfiles/debian9/Dockerfile b/Dockerfiles/debian9/Dockerfile
--- a/Dockerfiles/debian9/Dockerfile
+++ b/Dockerfiles/debian9/Dockerfile
@@ -1,14 +1,12 @@
+#For Debian 9
 FROM debian:stretch-slim
 
-LABEL maintainer="armand@nginx.com"
+LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-# Install prerequisite packages:
-RUN apt-get update
-RUN apt-get install -y apt-transport-https lsb-release ca-certificates wget dnsutils
-#RUN apt-get install -y vim # vi for config file editing
+# Download optional tools:
+#RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install --no-install-recommends vim-tiny && rm -rf /var/lib/apt/lists/* # vi for config file editing
 
 ## Install Nginx Plus
-
 # Download certificate and key from the customer portal https://cs.nginx.com
 # and copy to the build context
 RUN mkdir -p /etc/ssl/nginx
@@ -16,47 +14,63 @@ COPY etc/ssl/nginx/nginx-repo.crt /etc/ssl/nginx/nginx-repo.crt
 COPY etc/ssl/nginx/nginx-repo.key /etc/ssl/nginx/nginx-repo.key
 RUN chmod 644 /etc/ssl/nginx/*
 
-# Install method A. Install NGINX Plus from repo
-# Get other files required for installation
-RUN wget http://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key
-RUN printf "deb https://plus-pkgs.nginx.com/ubuntu `lsb_release -cs` nginx-plus\n" | tee /etc/apt/sources.list.d/nginx-plus.list
-RUN wget -P /etc/apt/apt.conf.d https://cs.nginx.com/static/files/90nginx
-RUN apt-get update
-RUN apt-get -y install nginx-plus
+# Install NGINX Plus
+RUN set -x \
+  && apt-get update && apt-get upgrade -y \
+  && apt-get install --no-install-recommends --no-install-suggests -y apt-transport-https ca-certificates gnupg1 curl python2.7 procps net-tools vim-tiny joe jq less \
+  && \
+  NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+  found=''; \
+  for server in \
+    ha.pool.sks-keyservers.net \
+    hkp://keyserver.ubuntu.com:80 \
+    hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu \
+  ; do \
+    echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+    apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+  done; \
+  test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+  echo "Acquire::https::plus-pkgs.nginx.com::Verify-Peer \"true\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::Verify-Host \"true\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::SslCert     \"/etc/ssl/nginx/nginx-repo.crt\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::SslKey      \"/etc/ssl/nginx/nginx-repo.key\";" >> /etc/apt/apt.conf.d/90nginx \
+  && printf "deb https://plus-pkgs.nginx.com/debian stretch nginx-plus\n" > /etc/apt/sources.list.d/nginx-plus.list \
+  && apt-get update && apt-get install -y nginx-plus \
+  && rm -rf /var/lib/apt/lists/*
 
 ## Optional: Install NGINX Plus Modules from repo
-#RUN apt-get install -y nginx-plus-module-modsecurity
-#RUN apt-get install -y nginx-plus-module-geoip
-#RUN apt‑get install -y nginx-plus-module-njs
-
-# Install method B. "Offine" Install NGINX Plus from .rpm
-# COPY install/nginx-plus_15-1~xenial_amd64.deb /tmp/nginx-plus_15-1~xenial_amd64.deb
-# RUN dpkg -i /tmp/nginx-plus_15-1~xenial_amd64.deb
-
-## Optional: Install NGINX Plus Modules from .deb (ensure dependencies are installed first)
-# Example:
-# RUN apt-get install -y libedit2
-# COPY install/nginx-plus-module-njs_15+0.2.0-1~xenial_amd64.deb /tmp/nginx-plus-module-njs_15+0.2.0-1~xenial_amd64.deb
-# RUN dpkg -i /tmp/nginx-plus-module-njs_15+0.2.0-1~xenial_amd64.deb
+# See https://www.nginx.com/products/nginx/modules
+# RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install --no-install-recommends nginx-plus-module-modsecurity && rm -rf /var/lib/apt/lists/*
+# RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install --no-install-recommends nginx-plus-module-geoip && rm -rf /var/lib/apt/lists/*
+# RUN DEBIAN_FRONTEND=noninteractive apt-get -qq -y install --no-install-recommends nginx-plus-module-njs && rm -rf /var/lib/apt/lists/*
 
 # Optional: COPY over any of your SSL certs for HTTPS servers
-# Example:
-#COPY etc/ssl/nginx/www.example.com.crt /etc/ssl/nginx/www.example.com.crt
-#COPY etc/ssl/nginx/www.example.com.key /etc/ssl/nginx/www.example.com.key
+# e.g.
+#COPY etc/ssl/www.example.com.crt /etc/ssl/www.example.com.crt
+#COPY etc/ssl/www.example.com.key /etc/ssl/www.example.com.key
 
 # Optional: Create cache folder and set permissions for proxy caching
-#CMD mkdir -p /var/cache/nginx
-#CMD chown -R nginx /var/cache/nginx
+#CMD mkdir -p /var/cache/nginx \
+#&& chown -R nginx /var/cache/nginx
+
+# Remove default nginx config
+RUN rm /etc/nginx/conf.d/default.conf
+# COPY /etc/nginx (Nginx configuration) directory
+COPY etc/nginx /etc/nginx
+RUN chown -R nginx:nginx /etc/nginx
 
 # Forward request logs to docker log collector
-RUN ln -sf /dev/stdout /var/log/nginx/access.log
-RUN ln -sf /dev/stderr /var/log/nginx/error.log
+RUN ln -sf /dev/stdout /var/log/nginx/access.log \
+&& ln -sf /dev/stderr /var/log/nginx/error.log
 
-# COPY /etc/nginx (Nginx configuration) directory and other directories as
-# necessary, for example, /usr/share/nginx/html for static files
-COPY etc/nginx /etc/nginx
-#COPY usr/share/nginx/html /usr/share/nginx/html # Optional
+# Raise the limits to successfully run benchmarks
+RUN ulimit -c -m -s -t unlimited
+
+# Remove the cert/keys from the image
+RUN rm /etc/ssl/nginx/nginx-repo.crt /etc/ssl/nginx/nginx-repo.key
 
 # EXPOSE ports, HTTP 80, HTTPS 443 and, Nginx status page 8080
-EXPOSE 80 8080 443
+EXPOSE 80 443 8080
+STOPSIGNAL SIGTERM
 CMD ["nginx", "-g", "daemon off;"]
